services:
  - type: web                 # <- obligatorio
    name: biocrowny-api
    runtime: python          #  <-- clave correcta
    buildCommand: |
      pip install -r requirements.txt
    startCommand: >
      gunicorn -b 0.0.0.0:8000 app:app
